echo ""
echo ""
echo ""
echo "ARE YOU READY FOR START NOW"
echo ""
echo ""
echo ""
echo "LET'S SUBSCRIBE PORMES17"
echo ""
echo ""
echo ""
echo "WAITING FOR STARTED"
echo ""
echo ""
echo ""

pkg install && pkg update && pkg upgrade
pkg install root-repo -y
pkg install unstable-repo -y
pkg install x11-repo -y
pkg install science-repo -y
pkg install game-repo -y
pkg install clang -y
pkg install vlang -y
pkg install slang -y
pkg install golang -y
pkg install 8086tiny -y
pkg install aalib -y
pkg install aapt -y
pkg install abduco -y
pkg install abook -y
pkg install ack-grep -y
pkg install acr -y
pkg install algernon -y
pkg install alpine -y
pkg install antibody -y
pkg install antiword -y
pkg install apache2 -y
pkg install apksigner -y
pkg install apr-util -y
pkg install apr -y
pkg install apt -y
pkg install aptly -y
pkg install argp -y
pkg install aria2 -y
pkg install arj -y
pkg install automake -y
pkg install asciinema -y
pkg install asciidoc -y
pkg install asciidoctor -y
pkg install aspell -y
pkg install assimp -y
pkg install atomicparsley -y
pkg install at -y
pkg install attr -y
pkg install autoconf -y
pkg install autossh -y
pkg install axel -y
pkg install babl -y
pkg install barcode -y
pkg install bash-completion -y
pkg install bash -y
pkg install bat -y
pkg install bc -y
pkg install beanshell -y
pkg install bgrep -y
pkg install binutils -y
pkg install bison -y
pkg install bitcoin -y
pkg install blackbox -y
pkg install blogc -y
pkg install bmon -y
pkg install boinc -y
pkg install boinctui -y
pkg install boost -y
pkg install borgbackup -y
pkg install brotli -y
pkg install build-essential -y
pkg install busybox -y
pkg install bvi -y
pkg install byobu -y
pkg install c-ares -y
pkg install c-toxcore -y
pkg install ca-certificates -y
pkg install cabextract -y
pkg install caddy -y
pkg install calc -y
pkg install calcurse -y
pkg install capstone -y
pkg install cava -y
pkg install ccache -y
pkg install ccnet -y
pkg install ccrypt -y
pkg install cfengine -y
pkg install cgdb -y
pkg install chezmoi -y
pkg install chromaprint -y
pkg install cicada -y
pkg install clamav -y
pkg install cmake -y
pkg install cmark -y
pkg install cmatrix -y
pkg install cmus -y
pkg install cmusfm -y
pkg install codecrypt -y
pkg install colordiff -y
pkg install command-not-found -y
pkg install coreutils -y
pkg install corkscrew -y
pkg install cowsay -y
pkg install cpio -y
pkg install cppi -y
pkg install cronie -y
pkg install crunch -y
pkg install cryptopp -y
pkg install cscope -y
pkg install ctags -y
pkg install ctypes-sh -y
pkg install curl -y
pkg install cvs -y
pkg install daemonize -y
pkg install darkhttpd -y
pkg install dart -y
pkg install dash -y
pkg install dasm -y
pkg install datamash -y
pkg install dcraw -y
pkg install ddrescue -y
pkg install debianutils -y
pkg install debootstrap -y
pkg install deutex -y
pkg install dialog -y
pkg install dictd -y
pkg install diffutils -y
pkg install dirb -y
pkg install direnv -y
pkg install direvent -y
pkg install diskus -y
pkg install dns2tcp -y
pkg install dnsmap -y
pkg install dnsutils -y
pkg install docbook-xml -y
pkg install docbook-xsl -y
pkg install dos2unix -y
pkg install double-conversion -y
pkg install doxygen -y
pkg install dpkg -y
pkg install dropbear -y
pkg install dtc -y
pkg install dte -y
pkg install duc -y
pkg install dvtm -y
pkg install dx -y
pkg install e2fsprogs -y
pkg install ecj -y
pkg install ed -y
pkg install electric-fence -y
pkg install elinks -y
pkg install elixir -y
pkg install elvish -y
pkg install emacs -y
pkg install entr -y
pkg install erlang -y
pkg install espeak -y
pkg install exa -y
pkg install exiftool -y
pkg install exiv2 -y
pkg install expect -y
pkg install fakeroot -y
pkg install fasd -y
pkg install fastmod -y
pkg install fd -y
pkg install fdupes -y
pkg install ffmpeg -y
pkg install fftw -y
pkg install figlet -y
pkg install file -y
pkg install finch -y
pkg install findutils -y
pkg install fish -y
pkg install flex -y
pkg install fmt -y
pkg install fontconfig -y
pkg install fortune -y
pkg install fossil -y
pkg install freeimage -y
pkg install freetype -y
pkg install fribidi -y
pkg install frobtads -y
pkg install fselect -y
pkg install fsmon -y
pkg install fwknop -y
pkg install fzf -y
pkg install game-repo -y
pkg install gatling -y
pkg install gawk -y
pkg install gbt -y
pkg install gcal -y
pkg install gdb -y
pkg install gdbm -y
pkg install gdk-pixbuf -y
pkg install gegl -y
pkg install geoip2-database -y
pkg install getconf -y
pkg install geth -y
pkg install gettext -y
pkg install gflags -y
pkg install gh -y
pkg install ghostscript -y
pkg install giflib -y
pkg install gifsicle -y
pkg install gifski -y
pkg install git-crypt -y
pkg install git-delta -y
pkg install git-lfs -y
pkg install git -y
pkg install gitea -y
pkg install gkermit -y
pkg install glib -y
pkg install global -y
pkg install gmic -y
pkg install gnuit -y
pkg install gnunet -y
pkg install gnupg -y
pkg install gnuplot -y
pkg install gnurl -y
pkg install go-findimagedupes -y
pkg install goaccess -y
pkg install golang -y
pkg install google-glog -y
pkg install googletest -y
pkg install gotty -y
pkg install gperf -y
pkg install gpgme -y
pkg install gpsbabel -y
pkg install graphicsmagick -y
pkg install graphviz -y
pkg install grep -y
pkg install gsl -y
pkg install gst-plugins-bad -y
pkg install gst-plugins-base -y
pkg install gst-plugins-good -y
pkg install gst-plugins-ugly -y
pkg install gstreamer -y
pkg install gtypist -y
pkg install gumbo-parser -y
pkg install gzip -y
pkg install harfbuzz -y
pkg install hashdeep -y
pkg install help2man -y
pkg install hexcurse -y
pkg install hexedit -y
pkg install hexyl -y
pkg install heyu -y
pkg install hfsutils -y
pkg install hiptext -y
pkg install hoedown -y
pkg install hollywood -y
pkg install html2txt -y
pkg install htop -y
pkg install httping -y
pkg install httrack -y
pkg install hub -y
pkg install hugo -y
pkg install hunspell-en-us -y
pkg install hunspell-ru -y
pkg install hunspell -y
pkg install hydra -y
pkg install hyperfine -y
pkg install i2pd -y
pkg install i3 -y
pkg install icecast -y
pkg install imagemagick -y
pkg install imgflo -y
pkg install imlib2 -y
pkg install indent -y
pkg install inetutils -y
pkg install inotify-tools -y
pkg install ipcalc -y
pkg install iperf3 -y
pkg install ipfs -y
pkg install ipmitool -y
pkg install ired -y
pkg install irssi -y
pkg install isync -y
pkg install iverilog -y
pkg install iw -y
pkg install iwyu -y
pkg install jfrog-cli -y
pkg install jftui -y
pkg install jhead -y
pkg install jo -y
pkg install joe -y
pkg install jp2a -y
pkg install jpegoptim -y
pkg install jq -y
pkg install json-c -y
pkg install json-glib -y
pkg install jsoncpp -y
pkg install k2pdfopt -y
pkg install kakoune -y
pkg install keybase -y
pkg install keychain -y
pkg install keystone -y
pkg install kibi -y
pkg install knockd -y
pkg install kona -y
pkg install krb5 -y
pkg install kubectl -y
pkg install lastpass-cli -y
pkg install lazyread -y
pkg install ldc -y
pkg install ldns -y
pkg install ledger -y
pkg install leptonica -y
pkg install less -y
pkg install lesspipe -y
pkg install leveldb -y
pkg install lf -y
pkg install lftp -y
pkg install lhasa -y
pkg install libacl -y
pkg install libandroid-glob -y
pkg install libandroid-shmem -y
pkg install libandroid-spawn -y
pkg install libandroid-support -y
pkg install libao -y
pkg install libarchive -y
pkg install libass -y
pkg install libassuan -y
pkg install libbsd -y
pkg install libbz2 -y
pkg install libc++ -y
pkg install libcaca -y
pkg install libcairo -y
pkg install libcap -y
pkg install libcln -y
pkg install libcoap -y
pkg install libconfig -y
pkg install libconfuse -y
pkg install libcroco -y
pkg install libcrypt -y
pkg install libcue -y
pkg install libcurl -y
pkg install libdav1d -y
pkg install libdb -y
pkg install libdispatch -y
pkg install libduktape -y
pkg install libebml -y
pkg install libedit -y
pkg install libelf -y
pkg install libev -y
pkg install libevent -y
pkg install libexif -y
pkg install libexpat -y
pkg install libffi -y
pkg install libflac -y
pkg install libgc -y
pkg install libgcrypt -y
pkg install libgd -y
pkg install libgfshare -y
pkg install libgit2 -y
pkg install libgmime -y
pkg install libgmp -y
pkg install libgnutls -y
pkg install libgpg-error -y
pkg install libgraphite -y
pkg install libgrpc -y
pkg install libgsasl -y
pkg install libical -y
pkg install libice -y
pkg install libiconv -y
pkg install libicu -y
pkg install libid3tag -y
pkg install libidn -y
pkg install libidn2 -y
pkg install libisl -y
pkg install libjansson -y
pkg install libjasper -y
pkg install libjpeg-turbo -y
pkg install libksba -y
pkg install libllvm -y
pkg install liblmdb -y
pkg install liblua -y
pkg install liblua52 -y
pkg install libluajit -y
pkg install liblz4 -y
pkg install liblzma -y
pkg install liblzo -y
pkg install libmaa -y
pkg install libmad -y
pkg install libmatroska -y
pkg install libmaxminddb -y
pkg install libmcrypt -y
pkg install libmediainfo -y
pkg install libmesode -y
pkg install libmhash -y
pkg install libmicrohttpd -y
pkg install libmnl -y
pkg install libmosquitto -y
pkg install libmp3lame -y
pkg install libmp3splt -y
pkg install libmpc -y
pkg install libmpdclient -y
pkg install libmpfr -y
pkg install libmsgpack -y
pkg install libnet -y
pkg install libnettle -y
pkg install libnfs -y
pkg install libnftnl -y
pkg install libnghttp2 -y
pkg install libnl -y
pkg install libnpth -y
pkg install libogg -y
pkg install liboggz -y
pkg install libopus -y
pkg install libopusenc -y
pkg install libotr -y
pkg install libowfat -y
pkg install libcap -y
pkg install libpipeline -y
pkg install libpixman -y
pkg install libpng -y
pkg install libpopt -y
pkg install libprotobuf-c -y
pkg install libprotobuf -y
pkg install libpsl -y
pkg install libqrencode -y
pkg install libraqm -y
pkg install librsvg -y
pkg install librsync -y
pkg install libsasl -y
pkg install libsearpc -y
pkg install libsignal-protocol-c -y
pkg install libsigsegv -y
pkg install libsm -y
pkg install libsndfile -y
pkg install libsodium -y
pkg install libsoup libsoxr -y
pkg install libsqlite -y
pkg install libssh -y-y
pkg install libssh2 -y
pkg install libtalloc -y
pkg install libtermkey -y
pkg install libtheora-y
pkg install libtiff -y
pkg install libtirpc -y
pkg install libtool -y
pkg install libtorrent -y
pkg install libunibilium -y
pkg install libunistring -y
pkg install libusb -y
pkg install libuuid -y
pkg install libuv -y
pkg install libvidstab -y
pkg install libvorbis -y
pkg install libvpx -y
pkg install libvterm -y
pkg install libwebp -y
pkg install libwebsockets  -y
pkg install libx11 -y
pkg install libx265 -y
pkg install libxapian -y
pkg install libxau -y
pkg install libxcb -y
pkg install libxdmcp -y
pkg install libxext -y
pkg install libxft -y
pkg install libxml2 -y
pkg install libxrender -y
pkg install libxslt -y
pkg install libxss -y
pkg install libxt -y
pkg install libyaml -y
pkg install libzen -y
pkg install libzim -y
pkg install libzip -y
pkg install libzmq -y
pkg install libzopfli -y
pkg install lighttpd -y
pkg install links -y
pkg install linux-man-pages -y
pkg install littlecms -y
pkg install llbuild -y
pkg install lldb -y
pkg install lnd -y
pkg install loksh -y
pkg install lsof -y
pkg install ltrace -y
pkg install lua-lpeg -y
pkg install luarocks -y
pkg install luv -y
pkg install lynx -y
pkg install lzip -y
pkg install lzop-y
pkg install m4 -y
pkg install make -y
pkg install man -y
pkg install mariadb -y
pkg install mathomatic -y
pkg install mbedtls -y
pkg install mc -y
pkg install mdns-scan -y
pkg install mdp -y
pkg install mediainfo -y
pkg install megatools -y
pkg install memcached -y
pkg install mg -y
pkg install micro -y
pkg install mime-support -y
pkg install minicom -y
pkg install miniupnpc -y
pkg install mksh -y
pkg install mktorrent -y
pkg install mkvtoolnix -y
pkg install mlocate -y
pkg install moreutils -y
pkg install morse2ascii -y
pkg install mosh -y
pkg install most -y
pkg install mp3splt -y
pkg install mpc -y
pkg install mpd -y
pkg install mpdscribble -y
pkg install mpv -y
pkg install msmtp -y
pkg install mtd-utils -y
pkg install mtools -y
pkg install mu -y
pkg install muchsync -y
pkg install multitail -y
pkg install mupdf -y
pkg install music-file-organizer -y
pkg install mutt -y
pkg install myrepos -y
pkg install nano -y
pkg install natpmpc -y
pkg install ncdc -y
pkg install ncdu -y
pkg install ncmpcpp -y
pkg install ncompress -y
pkg install ncurses -y
pkg install ndk-multilib -y
pkg install ndk-sysroot -y
pkg install ne -y
pkg install neofetch -y
pkg install neovim -y
pkg install net-tools -y
pkg install netpbm -y
pkg install netsed -y
pkg install newsboat -y
pkg install nginx -y
pkg install nim -y
pkg install ninja -y
pkg install nmap -y
pkg install nnn -y
pkg install nodejs-lts -y
pkg install notmuch -y
pkg install nushell -y
pkg install nyancat -y
pkg install nzbget -y
pkg install o-editor -y
pkg install oathtool -y
pkg install obfs4proxy -y
pkg install ocrad -y
pkg install odt2txt -y
pkg install okc-agents -y
pkg install oleo -y
pkg install oniguruma -y
pkg install openal-soft -y
pkg install openjpeg -y
pkg install openssh -y
pkg install openssl -y
pkg install optipng -y
pkg install opus-tools -y
pkg install opusfile -y
pkg install ossp-uuid -y
pkg install p7zip -y
pkg install pango -y
pkg install paperkey -y
pkg install par2 -y
pkg install parallel -y
pkg install parted -y
pkg install pass-otp -y
pkg install pass -y
pkg install pastebinit -y
pkg install patch -y
pkg install patchelf -y-y
pkg install pathpicker -y
pkg install pcaudiolib -y
pkg install pcre -y
pkg install pdf2svg -y
pkg install pdfgrep -y
pkg install perl -y
pkg install pforth -y
pkg install php -y
pkg install pianobar -y
pkg install pick -y
pkg install picolisp -y
pkg install pigz -y
pkg install pinentry -y
pkg install pkg-config -y
pkg install play-audio -y
pkg install plzip -y
pkg install pngquant -y
pkg install polipo -y
pkg install poppler -y
pkg install postgresql -y
pkg install potrace -y
pkg install privoxy -y
pkg install procps -y
pkg install profanity -y
pkg install progress -y
pkg install proot-distro -y
pkg install proot -y
pkg install proxmark3 -y
pkg install proxychains-ng -y
pkg install psmisc -y
pkg install psutils -y
pkg install pulseaudio -y
pkg install pup -y
pkg install pure-ftpd -y
pkg install pv -y
pkg install pwgen -y
pkg install python -y
pkg install python2 -y
pkg install qalc -y
pkg install qemu-system-x86_64-headless -y
pkg install qpdf -y
pkg install quickjs -y
pkg install radare2 -y
pkg install ragel -y
pkg install ranger -y
pkg install rclone -y
pkg install rcm -y
pkg install rcs -y
pkg install rcshell -y
pkg install rdiff-backup -y
pkg install readline -y
pkg install recutils -y
pkg install redir -y
pkg install redis -y
pkg install remind -y
pkg install renameutils -y
pkg install resolv-conf -y
pkg install restic -y
pkg install rgbds -y
pkg install rhash -y
pkg install rinetd -y
pkg install ripgrep -y
pkg install rlwrap -y
pkg install root-repo -y
pkg install rsnapshot -y
pkg install rsync -y-y
pkg install rtmpdump -y
pkg install rtorrent -y
pkg install ruby -y
pkg install ruby-ri -y
pkg install runit -y
pkg install rush -y
pkg install rust -y
pkg install samefile -y
pkg install sc-im -y
pkg install sc -y
pkg install science-repo -y
pkg install screen -y
pkg install screenfetch-y
pkg install scrub -y
pkg install scrypt -y
pkg install sdcv -y
pkg install seafile-client -y
pkg install seccure -y
pkg install secure-delete -y
pkg install sed -y-y
pkg install sensible-utils -y
pkg install serf -y
pkg install sharutils -y
pkg install shc -y
pkg install shell2http -y
pkg install shellharden -y
pkg install shellinabox -y
pkg install shfmt -y
pkg install silversearcher-ag -y
pkg install sl -y
pkg install slang -y
pkg install sleuthkit -y
pkg install socat -y
pkg install solidity -y
pkg install sox -y
pkg install speexdsp -y
pkg install spiped -y
pkg install sqlcipher -y
pkg install sqlmap -y
pkg install squid -y
pkg install sshpass -y
pkg install ssss -y
pkg install stag -y
pkg install starship -y
pkg install stdman -y
pkg install steghide -y
pkg install stfl -y
pkg install stow -y
pkg install strace -y
pkg install streamripper -y
pkg install stunnel -y
pkg install subversion -y
pkg install swaks -y
pkg install swi-prolog -y
pkg install swift -y 
pkg install swig -y
pkg install syncthing -y
pkg install ta-lib -y
pkg install taglib -y
pkg install tar -y
pkg install task-spooler -y
pkg install tasksh -y
pkg install taskwarrior -y
pkg install tcl -y
pkg install tcsh -y
pkg install teckit -y
pkg install tergent -y
pkg install termimage -y
pkg install termux-am -y
pkg install termux-api -y
pkg install termux-apt-repo -y
pkg install termux-auth -y
pkg install termux-create-package -y
pkg install termux-elf-cleaner -y
pkg install termux-exec -y
pkg install termux-keyring -y
pkg install termux-licenses -y
pkg install termux-services -y
pkg install termux-tools -y
pkg install teseq -y
pkg install tesseract -y
pkg install texinfo -y
pkg install texlive-bin -y
pkg install tidy -y
pkg install tig -y
pkg install tigervnc -y
pkg install timewarrior -y
pkg install tin-summer -y
pkg install tintin++ -y
pkg install tinyfugue -y
pkg install tinyproxy -y
pkg install tinyscheme -y
pkg install tk -y
pkg install tmate -y
pkg install tmux -y
pkg install toilet -y
pkg install tokei -y
pkg install tor -y
pkg install torsocks -y
pkg install toxic -y
pkg install tracepath -y
pkg install translate-shell -y
pkg install transmission -y
pkg install tree -y
pkg install tsocks -y
pkg install tsu -y
pkg install ttf-dejavu -y
pkg install tty-clock -y
pkg install ttyd -y
pkg install ttyrec -y
pkg install tweego -y
pkg install uftrace -y
pkg install unicorn -y
pkg install unifdef -y
pkg install units -y
pkg install unrar -y
pkg install unshield -y
pkg install unstable-repo -y
pkg install unzip -y
pkg install utf8cpp -y
pkg install utf8proc -y
pkg install utfdecode -y
pkg install util-linux -y
pkg install valac -y
pkg install valgrind -y
pkg install vcsh -y
pkg install vegeta -y
pkg install vifm -y
pkg install vim -y
pkg install virustotal-cli -y
pkg install vorbis-tools -y
pkg install vttest -y
pkg install vtutils -y
pkg install w3m -y
pkg install wcalc -y
pkg install weechat -y
pkg install wget -y
pkg install wireguard-tools -y
pkg install wol -y
pkg install wordgrinder -y
pkg install wren -y
pkg install wrk -y
pkg install wuzz -y
pkg install x11-repo -y
pkg install xcb-proto -y
pkg install xdelta3 -y
pkg install xmake -y
pkg install xmlsec -y
pkg install xmlstarlet -y
pkg install xorg-util-macros -y
pkg install xorgproto -y
pkg install xorriso -y
pkg install xtrans -y
pkg install xvidcore -y
pkg install yadm -y
pkg install yajl -y
pkg install yarn -y
pkg install yasm -y
pkg install youtubedr -y
pkg install z3 -y
pkg install zbar -y
pkg install zile -y
pkg install zip -y
pkg install zlib -y
pkg install zsh -y
pkg install zstd -y
pkg install zsync -y
gem update
pkg install metasploit -y
pkg install && pkg update && pkg upgrade

echo ""
echo "ALL DEPENDENCIES AND LIBRARY OF PACKAGING IS FINISHED"
echo "DON'T FORGET TO SUBSCRIBE PORMES17"
echo ""
echo ""
echo ""
echo ""
echo "ARE YOU PRO NOW"
echo "SUPPORT ME AND SUBSCRIBE PORMES17"
echo ""
echo "CODED BY PORMES17"
exit
